class Solution:
  def find_the_difference(self, s: str, t: str) -> str:
    
    code = 0

    for char in s:
      code -= ord(char)
    
    for char in t:
      code += ord(char)

    return chr(code)


# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:

# Input: s = "", t = "y"
# Output: "y"
